dist: trusty

sudo: required

addon_shortcuts:
  xcode64: &xcode64
    apt:
      packages:
        - libboost-all-dev

  clang38: &clang38
    apt:
      sources:
        - llvm-toolchain-trusty-3.8
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
      packages:
        - clang-3.8
        - libc++-dev
        - libboost-all-dev

  clang50: &clang50
    apt:
      sources:
        - llvm-toolchain-trusty-5.0
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
      packages:
        - clang-5.0
        - libc++-dev
        - libboost-all-dev

  clang60: &clang60
    apt:
      sources:
        - llvm-toolchain-trusty-6.0
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
      packages:
        - clang-6.0
        - libc++-dev
        - libboost-all-dev

  gcc48: &gcc48
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
        - libboost-all-dev

  gcc6: &gcc6
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-6
        - libboost-all-dev

  gcc7: &gcc7
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-7
        - libboost-all-dev

  gcc8: &gcc8
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-8
        - libboost-all-dev

addons:
  apt:
    update: true
    packages:
      - cmake

before_install:
  - curl -L http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main' | sudo tee /etc/apt/sources.list
  - chmod +x tests/build/cmake/run_tests.sh

matrix:
  include:
    - { env: 'STD=11 CXX=g++-4.8 CMAKEFLAGS="-fsanitize=address,memory,undefined,thread,leak -fuse-ld=gold"', addons: *gcc48 }
    - { env: 'STD=11 CXX=g++-6 CMAKEFLAGS="-fsanitize=address,memory,undefined,thread,leak -fuse-ld=gold"', addons: *gcc6 }
    - { env: 'STD=11 CXX=g++-6 CMAKEFLAGS=-DNO_DEPRECATED=YES', addons: *gcc6 }
    - { env: 'STD=11 CXX=g++-7 CMAKEFLAGS=-fsanitize=address,memory,undefined,thread,leak', addons: *gcc7 }
    - { env: 'STD=11 CXX=g++-7 CMAKEFLAGS=-DNO_DEPRECATED=YES', addons: *gcc7 }
    - { env: 'STD=11 CXX=g++-8 CMAKEFLAGS=-fsanitize=address,memory,undefined,thread,leak', addons: *gcc8 }
    - { env: 'STD=11 CXX=g++-8 CMAKEFLAGS=-DNO_DEPRECATED=YES', addons: *gcc8 }
    - { env: 'STD=11 CXX=clang++-3.8 CMAKEFLAGS="-fsanitize=address,memory,undefined,thread,leak"', addons: *clang38 }
    - { env: 'STD=11 CXX=clang++-5.0 CMAKEFLAGS="-fsanitize=address,memory,undefined,thread,leak"', addons: *clang50 }
    - { env: 'STD=11 CXX=clang++-6.0 CMAKEFLAGS="-fsanitize=address,memory,undefined,thread,leak"', addons: *clang60 }
    - { env: 'CXX=clang++', compiler: clang, osx_image: xcode6.4, addons: *xcode64}

  allow_failures:
    - { env: 'STD=11 CXX=clang++-3.8 CMAKEFLAGS="-fsanitize=address,memory,undefined,thread,leak"', addons: *clang38 }
    - { env: 'STD=11 CXX=clang++-5.0 CMAKEFLAGS="-fsanitize=address,memory,undefined,thread,leak"', addons: *clang50 }
    - { env: 'STD=11 CXX=clang++-6.0 CMAKEFLAGS="-fsanitize=address,memory,undefined,thread,leak"', addons: *clang60 }
    - { env: 'CXX=clang++', compiler: clang, osx_image: xcode6.4, addons: *xcode64}

script:
  - cd tests/build/cmake
  - cmake $CMAKEFLAGS .
  - make -j2
  - ./run_tests.sh

